global:
  envs:
    USER_BASE_DN: dc=sampleCiam.com
    ENVIRONMENT_NAME: seipoc
    DOMAIN_NAME: ping-devops.com
  labels:
    facile.pingidentity.cloud/admin-env-id: d159739d-9eeb-4c83-8208-551acfdda03e
    facile.pingidentity.cloud/admin-user-id: dd476d20-fbb0-44e8-b037-064ef51f1435
pingOne:
  envRegion: NA
  administration:
    useMyPing: true
    envId: d159739d-9eeb-4c83-8208-551acfdda03e
    adminUserId: dd476d20-fbb0-44e8-b037-064ef51f1435
    workerApp:
      id: 817ad030-8051-46e8-ab7a-e311fb46fca4
      secret: gY2YJH7cG.9Uug269pEQHeBlOgLUqVf4x_DRjh4B6gV933l6G3_w3hO7QZZ~GRqI
    pfLogonApp:
      id: 9b5e1668-cb7b-4cb0-8d07-9cacb362cf4b
      secret: G~2KgSygFRexdc1V8o8_YNojejM00rmVewo43jzgW40hp8sdC3gr9ApuD3YzcJ_1
    paLogonApp:
      id: 165cb48c-b2a2-4f30-ae78-6b517961d2c2
      secret: LFO8t~AyrgnVSnecZ11hBGE~~2eAM-PdN5DjnqFzkdwQP6vnbOj2FXfNMFMPMcxb
    pdLogonApp:
      id: 165cb48c-b2a2-4f30-ae78-6b517961d2c2
      secret: LFO8t~AyrgnVSnecZ11hBGE~~2eAM-PdN5DjnqFzkdwQP6vnbOj2FXfNMFMPMcxb
usePingConfig:
  enabled: true
baseline:
  directory:
    enabled: true
capabilities:
  authenticationAuthority:
    enabled: true
  multiFactorAuthentication:
    enabled: true
  accessManager:
    enabled: true
  dynamicAuthorization:
    enabled: true
  risk:
    enabled: true
  verify:
    enabled: true
useCases:
  ciba:
    enabled: true
  consentManagement:
    enabled: true
  delegatedAdministration:
    enabled: true
  accessControl:
    enabled: true
  scim:
    enabled: true
  socialConnections:
    enabled: true
  userProfiles:
    enabled: true
  verifyDemoEnv:
    enabled: true
ping-devops:
  pingfederate-admin:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/hinespj/seipoc.git
      SERVER_PROFILE_PATH: server-profile/pingfederate
      SERVER_PROFILE_BRANCH: main
    workload:
      type: StatefulSet
  pingfederate-engine:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/hinespj/seipoc.git
      SERVER_PROFILE_PATH: server-profile/pingfederate
      SERVER_PROFILE_BRANCH: main
      TAIL_LOG_FILES: /opt/out/instance/log/audit.log /opt/out/instance/log/server.log
      PF_LOG_LEVEL: DEBUG
  pingdirectory:
    enabled: true
  pingdatasync:
    enabled: true
  pingaccess-admin:
    enabled: true
  pingaccess-engine:
    enabled: true
    envs:
      TAIL_LOG_FILES: >-
        /opt/out/instance/log/pingaccess_engine_audit.log
        /opt/out/instance/log/pingaccess.log
  pingdatagovernance:
    enabled: false
  pingdatagovernancepap:
    enabled: false
  pingdelegator:
    enabled: true
